version: 33
jobs:
- name: Push to Github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/birdup000/ADHD-TaskManagementPanel
    userName: birdup000
    passwordSecret: access-token
    force: false
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger
    projects: ADHD-Panel
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
